### ISSUE TITLE
Serializing errors break mspack (panic: reflect.Set: value of type map[interface {}]interface {} is not assignable to type error)

### ISSUE THREAD

**Issue by santagada** [vmihailenco/msgpack#108]
Example code:

``` go
package main

import (
        "errors"
        "fmt"

        "gopkg.in/vmihailenco/msgpack.v2"
)

type APIRes struct {
        Code    int
        Message string
        Error   error
}

func main() {
        a := &APIRes{Error: errors.New("hi")}
        b := &APIRes{}
        buf, _ := msgpack.Marshal(a)
        msgpack.Unmarshal(buf, b)
        fmt.Print(b)
}
```

error:

```
panic: reflect.Set: value of type map[interface {}]interface {} is not assignable to type error

goroutine 1 [running]:
panic(0xe23c0, 0xc820076340)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
reflect.Value.assignTo(0xe1a40, 0xc82007a3f0, 0x15, 0x13a790, 0xb, 0x102d20, 0xc82007a258, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.3/libexec/src/reflect/value.go:2164 +0x3be
reflect.Value.Set(0x102d20, 0xc82007a258, 0x194, 0xe1a40, 0xc82007a3f0, 0x15)
        /usr/local/Cellar/go/1.6.3/libexec/src/reflect/value.go:1334 +0x95
gopkg.in/vmihailenco/msgpack.v2.(*Decoder).interfaceValue(0xc82007a3c0, 0x102d20, 0xc82007a258, 0x194, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode.go:226 +0xe3
gopkg.in/vmihailenco/msgpack.v2.decodeInterfaceValue(0xc82007a3c0, 0x102d20, 0xc82007a258, 0x194, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode_value.go:157 +0x7b
gopkg.in/vmihailenco/msgpack.v2.(*field).DecodeValue(0xc8200721c0, 0xc82007a3c0, 0x112b80, 0xc82007a240, 0x199, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/types.go:84 +0x99
gopkg.in/vmihailenco/msgpack.v2.decodeStructValue(0xc82007a3c0, 0x112b80, 0xc82007a240, 0x199, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode_map.go:215 +0x2a1
gopkg.in/vmihailenco/msgpack.v2.(*Decoder).DecodeValue(0xc82007a3c0, 0x112b80, 0xc82007a240, 0x199, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode.go:188 +0x98
gopkg.in/vmihailenco/msgpack.v2.(*Decoder).decode(0xc82007a3c0, 0xd5560, 0xc82007a240, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode.go:183 +0x4f1
gopkg.in/vmihailenco/msgpack.v2.(*Decoder).Decode(0xc82007a3c0, 0xc820041ee8, 0x1, 0x1, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode.go:65 +0xbd
gopkg.in/vmihailenco/msgpack.v2.Unmarshal(0xc82006e094, 0x17, 0x40, 0xc820041ee8, 0x1, 0x1, 0x0, 0x0)
        $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/decode.go:39 +0x37b
main.main()
        $GOPATH/src/test/t.go:20 +0x2ac
exit status 2
```

**Comment by vmihailenco** [comment]
Sorry, notification for this issue was lost in my inbox.

`errors.New("hi")` returns struct that is marshaled and decoded as `map` by default. So it works as expected...

The easiest solution is to change `Error   error` to `Error   string`. Probably this lib should do it by default...
