### ISSUE TITLE
panic: reflect.Value.Convert: value of type T cannot be converted to type map[string]interface {}

### ISSUE THREAD

**Issue by pftbest** [vmihailenco/msgpack#124]
Type `monitor.Telemetry` is defined as
```go
type TelemetryData interface{}
type Telemetry map[string]TelemetryData
```
```
panic: reflect.Value.Convert: value of type monitor.Telemetry cannot be converted to type map[string]interface {}

goroutine 1 [running]:
reflect.Value.Convert(0x4196960, 0xc4200fa1b0, 0x15, 0x428f320, 0x41939e0, 0x8, 0xc420074750, 0x42a05a0)
        /usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:2187 +0x202
gopkg.in/vmihailenco/msgpack%2ev2.encodeMapStringInterfaceValue(0xc4200fa570, 0x4196960, 0xc4200fa1b0, 0x15, 0x4196960, 0xc4200fa1b0)
        /Users/vadzim/Documents/gopath/src/gopkg.in/vmihailenco/msgpack.v2/encode_map.go:66 +0x103
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).EncodeValue(0xc4200fa570, 0x4196960, 0xc4200fa1b0, 0x15, 0x15, 0x0)
        /Users/vadzim/Documents/gopath/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:124 +0x8c
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).encode(0xc4200fa570, 0x4196960, 0xc4200fa1b0, 0x30, 0x41a9fa0)
        /Users/vadzim/Documents/gopath/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:119 +0x21c
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).Encode(0xc4200fa570, 0xc420051c30, 0x1, 0x1, 0x9, 0x9)
        /Users/vadzim/Documents/gopath/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:74 +0x5b
gopkg.in/vmihailenco/msgpack%2ev2.Marshal(0xc420051c30, 0x1, 0x1, 0xc4200f88a0, 0x40, 0x0, 0x0, 0x0)
        /Users/vadzim/Documents/gopath/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:34 +0x15a
```

**Comment by vmihailenco** [comment]
Thanks for the report - fixed in v2.8.4
