### ISSUE TITLE
decode exception, bug?

### ISSUE THREAD

**Issue by dearplain** [vmihailenco/msgpack#160]
go version go1.9.1 windows/amd64

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/vmihailenco/msgpack"
)

type Abc struct {
	BB   int
	Haha int
}

type Msg struct {
	ID  int
	Inf interface{}
}

func main() {

	var msg Msg
	msg.Inf = Abc{BB: 2, Haha: 3}
	var buf bytes.Buffer
	msgpack.NewEncoder(&buf).StructAsArray(true).Encode(msg)
	data := buf.Bytes()

	{
		var msgD Msg
		infD := &Abc{}
		msgD.Inf = infD
		msgpack.Unmarshal(data, &msgD)
		fmt.Println(msgD, infD)
	}

	{
		var msgD Msg
		infD := Abc{}
		msgD.Inf = infD
		msgpack.Unmarshal(data, &msgD)  // panic here
		fmt.Println(msgD)
	}

}

```

```
d:\code\code>code.exe
{0 0xc04200e130} &{2 3}
panic: reflect: reflect.Value.SetInt using unaddressable value

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x82)
        D:/go/src/reflect/value.go:228 +0x184
reflect.Value.SetInt(0x4d0520, 0xc04200e170, 0x82, 0x2)
        D:/go/src/reflect/value.go:1420 +0x36
github.com/vmihailenco/msgpack.decodeInt64Value(0xc0420380c0, 0x4d0520, 0xc04200e170, 0x82, 0x4d0520, 0xc04200e170)
        D:/golib/src/github.com/vmihailenco/msgpack/decode_number.go:279 +0x85
github.com/vmihailenco/msgpack.(*field).DecodeValue(0xc042036140, 0xc0420380c0, 0x4dd300, 0xc04200e170, 0x99, 0x4daa20, 0x4cb200)
        D:/golib/src/github.com/vmihailenco/msgpack/types.go:93 +0x89
github.com/vmihailenco/msgpack.decodeStructValue(0xc0420380c0, 0x4dd300, 0xc04200e170, 0x99, 0x4dd300, 0xc04200e170)
        D:/golib/src/github.com/vmihailenco/msgpack/decode_map.go:236 +0x196
github.com/vmihailenco/msgpack.(*Decoder).DecodeValue(0xc0420380c0, 0x4dd300, 0xc04200e170, 0x99, 0xc04200e170, 0x99)
        D:/golib/src/github.com/vmihailenco/msgpack/decode.go:201 +0x93
github.com/vmihailenco/msgpack.decodeInterfaceValue(0xc0420380c0, 0x4d7880, 0xc0420024a8, 0x194, 0x4d7880, 0xc0420024a8)
        D:/golib/src/github.com/vmihailenco/msgpack/decode_value.go:241 +0xeb
github.com/vmihailenco/msgpack.(*field).DecodeValue(0xc042036100, 0xc0420380c0, 0x4dd3a0, 0xc0420024a0, 0x199, 0x0, 0x0)
        D:/golib/src/github.com/vmihailenco/msgpack/types.go:93 +0x89
github.com/vmihailenco/msgpack.decodeStructValue(0xc0420380c0, 0x4dd3a0, 0xc0420024a0, 0x199, 0x4dd3a0, 0xc0420024a0)
        D:/golib/src/github.com/vmihailenco/msgpack/decode_map.go:236 +0x196
github.com/vmihailenco/msgpack.(*Decoder).DecodeValue(0xc0420380c0, 0x4dd3a0, 0xc0420024a0, 0x199, 0xc0420024a0, 0x199)
        D:/golib/src/github.com/vmihailenco/msgpack/decode.go:201 +0x93
github.com/vmihailenco/msgpack.(*Decoder).decode(0xc0420380c0, 0x4cb240, 0xc0420024a0, 0x4daca0, 0x4e7dc0)
        D:/golib/src/github.com/vmihailenco/msgpack/decode.go:196 +0x123
github.com/vmihailenco/msgpack.(*Decoder).Decode(0xc0420380c0, 0xc042061ec8, 0x1, 0x1, 0xc042058240, 0x1)
        D:/golib/src/github.com/vmihailenco/msgpack/decode.go:82 +0x76
github.com/vmihailenco/msgpack.Unmarshal(0xc042066028, 0x5, 0x40, 0xc042061ec8, 0x1, 0x1, 0x0, 0x0)
        D:/golib/src/github.com/vmihailenco/msgpack/decode.go:36 +0x237
main.main()
        d:/code/code/gotest.go:40 +0x545
```

**Comment by vmihailenco** [comment]
Library to not panic in such cases - thanks for the report.

**Comment by dearplain** [comment]
Wow, you're coding very fast!!
I think codec is doing right:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/ugorji/go/codec"
	"github.com/vmihailenco/msgpack"
)

type Abc struct {
	BB   int
	Haha int
}

type Msg struct {
	ID  int
	Inf interface{}
}

var MsgpackHandle = codec.MsgpackHandle{
	BasicHandle: codec.BasicHandle{
		EncodeOptions: codec.EncodeOptions{
			StructToArray: true,
		},
		DecodeOptions: codec.DecodeOptions{
			SignedInteger: true,
		},
	},
	RawToString: true,
}

func Decode(b []byte, sPtr interface{}) error {
	return codec.NewDecoderBytes(b, &MsgpackHandle).Decode(sPtr)
}

func main() {

	var msg Msg
	msg.Inf = Abc{BB: 2, Haha: 3}
	var buf bytes.Buffer
	msgpack.NewEncoder(&buf).StructAsArray(true).Encode(msg)
	data := buf.Bytes()
	fmt.Printf("%x\n", data)

	{
		var msgD Msg
		infD := Abc{}
		msgD.Inf = infD
		msgpack.Unmarshal(data, &msgD)
		fmt.Println(msgD) // {0 {0 0}}
	}

	{
		var msgD Msg
		infD := Abc{}
		msgD.Inf = infD
		Decode(data, &msgD)
		fmt.Println(msgD) // {0 {2 3}}
	}

}

```

**Comment by vmihailenco** [comment]
And what is the rationale behind the fact that when decoding into `msgD` data ends up being in `msgD.Inf`? And that `msgD.Inf` must be an interface{}. What is good about it?

**Comment by dearplain** [comment]
consider `Msg` is an inner message struct use by workers, `Msg` can bring any msg to workers with some extra fields.

**Comment by vmihailenco** [comment]
Okay, it is still not obvious why the result is not `{2 {0 0}}` or `{2 {3 0}}`. Anyway that feature was never supported by this lib and I still don't see its usefulness. E.g. why not to use map and decode into `map[string]interface{}` if you want arbitrary number of fields. So I will keep this issue closed.

**Comment by dearplain** [comment]
ok, thanks for you reply, has a good weekend.

**Comment by morganwu** [comment]
I may have a similar issue, here is my test code:
```go
package main

import (
	"fmt"
	"github.com/vmihailenco/msgpack"
)

type Result struct {
	Data interface{}
	//Error error
}

type User struct {
	Name string
}

func main() {

	in := &Result{}
	out := &Result{
		Data: &User{},
	}

	bts, _ := msgpack.Marshal(in)

	err := msgpack.Unmarshal(bts, out)
	if err != nil {
		fmt.Println(err)
	}
}
```
My expectation is out.Data should be left blank or nil if in.Data == nil, but not panic, maybe that is not msgpack works like?
