### ISSUE TITLE
Unmarshal panic on valid msgpack data

### ISSUE THREAD

**Issue by scunningham** [vmihailenco/msgpack#260]
Msgpack format does not disallow a map whose key is another map.  Given this payload, the library panics.  Here's an example in v2:

```
package main

import (
	"fmt"
	"gopkg.in/vmihailenco/msgpack.v2"
)

func main() {
	fmt.Println("Hello, playground")
	
	data := []byte{0x81, 0x81, 0xa1, 0x78, 0xc3, 0xc3}
	
	var msg interface{}
	err := msgpack.Unmarshal(data, &msg)
	
	fmt.Println(err, msg)
}
```
On execution:
```
Hello, playground
panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
gopkg.in/vmihailenco/msgpack%2ev2.decodeMap(0xc00005c050, 0x0, 0x0, 0x0, 0x478288)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode_map.go:71 +0x17d
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).DecodeMap(...)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode_map.go:187
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).DecodeInterface(0xc00005c050, 0x40d155, 0xc00006ad18, 0xc00006acb0, 0x4783a2)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:258 +0x99c
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).interfaceValue(0xc00005c050, 0x4cbbe0, 0xc0000102d0, 0x194, 0x4c0180, 0x50adc0)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:218 +0x32
gopkg.in/vmihailenco/msgpack%2ev2.decodeInterfaceValue(0xc00005c050, 0x4cbbe0, 0xc0000102d0, 0x194, 0x4cbbe0, 0xc00005c050)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode_value.go:241 +0xf2
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).DecodeValue(0xc00005c050, 0x4cbbe0, 0xc0000102d0, 0x194, 0xc0000102d0, 0x194)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:185 +0x8c
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).decode(0xc00005c050, 0x4c0180, 0xc0000102d0, 0x30, 0x4d6600)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:180 +0x171
gopkg.in/vmihailenco/msgpack%2ev2.(*Decoder).Decode(0xc00005c050, 0xc00006af48, 0x1, 0x1, 0xc000062901, 0xc0000102d0)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:66 +0x6c
gopkg.in/vmihailenco/msgpack%2ev2.Unmarshal(0xc00002c008, 0x6, 0x6, 0xc00006af48, 0x1, 0x1, 0x0, 0x0)
	/tmp/gopath973180439/pkg/mod/gopkg.in/vmihailenco/msgpack.v2@v2.9.1/decode.go:37 +0xaa
main.main()
	/tmp/sandbox071138712/prog.go:14 +0x11c
```

Library fails similarly on v4 and v5.  I would expect an error returned, not a panic.  The user of the library does not always have control of the input data; forcing the caller to handle a panic is unexpected.

**Comment by scunningham** [comment]
PR for v5: https://github.com/vmihailenco/msgpack/pull/265

Seems like a simple fix.
